### ISSUE TITLE
GPS data is incorrect

### ISSUE THREAD

**Issue by ghost** [Llamabagel/TranspoIssues#64]
I discovered this GPS bug tonight whilst waiting for the 12 at Rideau. 

Attached is a screengrab of where the GPS was pointing for the 12.

Steps taken to get screenshot.
From Favourites:
- clicked on Rideau 3A (Rideau St)
- clicked on GPS for 12 Blair
- zoomed out to find the bus
![c4lfedswqaeiphr](https://cloud.githubusercontent.com/assets/25650245/22763111/ca65080c-ee30-11e6-86e4-b46265da79b8.jpg)

**Comment by dellisd** [comment]
Looks like it defaulted to the coordinates 0.0/0.0. Seeing as the 12 starts at Rideau, I don't think GPS data should have been available for any of those buses, but seeing as that isn't the case, I'll add some extra checks to prevent this from happening again.

Thanks for the report!

**Comment by dellisd** [comment]
Fixed in 1.2.3
